### We import the necessary libraries and packages

In [1]:
from common import sys
from common import os

module_path = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
sys.path.append(module_path)

In [2]:
# Import dataframe and functions from package

from package.variables import df
from package.custom_functions import format_number, clean_string

### Check the info of DataFrame

In [3]:
df.head(10)

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
5,5,Minecraft,"Nov 18, 2011",['Mojang Studios'],4.3,2.3K,2.3K,"['Adventure', 'Simulator']",Minecraft focuses on allowing the player to ex...,['Minecraft is what you make of it. Unfortunat...,33K,1.8K,1.1K,230
6,6,Omori,"Dec 25, 2020","['OMOCAT', 'PLAYISM']",4.2,1.6K,1.6K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...",A turn-based surreal horror RPG in which a chi...,"[""The best game I've played in my life"", ""omor...",7.2K,1.1K,4.5K,3.8K
7,7,Metroid Dread,"Oct 07, 2021","['Nintendo', 'MercurySteam']",4.3,2.1K,2.1K,"['Adventure', 'Platform']",Join intergalactic bounty hunter Samus Aran in...,['Have only been a Metroid fan for couple of y...,9.2K,759,3.4K,3.3K
8,8,Among Us,"Jun 15, 2018",['InnerSloth'],3.0,867,867,"['Indie', 'Strategy']",Join your crew-mates in a multiplayer game of ...,"[""it's a solid party game. i'm bad at lying th...",25K,470,776,126
9,9,NieR: Automata,"Feb 23, 2017","['PlatinumGames', 'Square Enix']",4.3,2.9K,2.9K,"['Brawler', 'RPG']","NieR: Automata tells the story of androids 2B,...","['Holy shit', 'im carrying the weight of the w...",18K,1.1K,6.2K,3.6K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

In [5]:
df.isnull().sum()

Unnamed: 0            0
Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

## Clean Dataframe

In [6]:
df["Rating"] = df["Rating"].fillna(0)
df.isnull().sum()

Unnamed: 0           0
Title                0
Release Date         0
Team                 1
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Summary              1
Reviews              0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
dtype: int64

### We will change the columns name and delete some columns

In [7]:
df.rename(columns={df.columns[0]: "Id"}, inplace=True)
df.rename(mapper=lambda x: x.replace(" ", ""), axis=1, inplace=True)

In [8]:
df.drop(columns=["Summary", "Reviews"], inplace=True)
df.columns

Index(['Id', 'Title', 'ReleaseDate', 'Team', 'Rating', 'TimesListed',
       'NumberofReviews', 'Genres', 'Plays', 'Playing', 'Backlogs',
       'Wishlist'],
      dtype='object')

### We will change the dtype

In [9]:
cols_to_numbers = ["TimesListed", "NumberofReviews", "Plays", "Playing", "Backlogs", "Wishlist"]

df_copy_cols = df[cols_to_numbers].copy()
df.update(df_copy_cols.applymap(format_number))

In [10]:
# For each column, we change the dtype
for col in cols_to_numbers:
    df[col] = df[col].astype("int64")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               1512 non-null   int64
 1   Title            1512 non-null   object
 2   ReleaseDate      1512 non-null   object
 3   Team             1511 non-null   object
 4   Rating           1512 non-null   float64
 5   TimesListed      1512 non-null   int64
 6   NumberofReviews  1512 non-null   int64
 7   Genres           1512 non-null   object
 8   Plays            1512 non-null   int64
 9   Playing          1512 non-null   int64
 10  Backlogs         1512 non-null   int64
 11  Wishlist         1512 non-null   int64
dtypes: float64(1), int64(7), object(4)
memory usage: 141.9+ KB

In [11]:
# We apply the function to the columns for cleaning strings
df["Genres"] = df["Genres"].apply(clean_string)
df["Team"] = df["Team"].apply(clean_string)
df[["Genres", "Team"]].head(5)

,Genres,Team
0,"Adventure, RPG","Bandai Namco Entertainment, FromSoftware"
1,"Adventure, Brawler, Indie, RPG",Supergiant Games
2,"Adventure, RPG","Nintendo, Nintendo EPD Production Group No. 3"
3,"Adventure, Indie, RPG, Turn Based Strategy","tobyfox, 8-4"
4,"Adventure, Indie, Platform",Team Cherry

In [12]:
# Sort the values by Whishlist
df = df.sort_values(by="Rating", ascending=False)
df.head()

,Id,Title,ReleaseDate,Team,Rating,TimesListed,NumberofReviews,Genres,Plays,Playing,Backlogs,Wishlist
1252,1252,Elden Ring: Shadow of the Erdtree,releases on TBD,"FromSoftware, Bandai Namco Entertainment",4.8,18,18,"Adventure, RPG",1,0,39,146
1090,1090,The Great Ace Attorney 2: Resolve,"Aug 03, 2017",Capcom,4.6,386,386,"Adventure, Point-and-Click, Puzzle, Visual Novel",1100,75,771,468
1153,1153,Dwarf Fortress,"Dec 06, 2022","Bay 12 Games, Kitfox Games",4.6,48,48,"Indie, RPG, Simulator, Strategy",225,80,181,195
1104,1104,Sekiro: Shadows Die Twice - GOTY Edition,"Oct 28, 2020","Activision, FromSoftware",4.6,173,173,"Adventure, Brawler, RPG",1400,153,461,373
43,43,Outer Wilds,"May 28, 2019","Mobius Digital, Annapurna Interactive",4.6,1800,1800,"Adventure, Indie, Puzzle, Simulator",7700,661,4800,3100

In [13]:
# We drop the duplicates values by Title
df.drop_duplicates(subset="Title", keep="first", inplace=True)

In [14]:
df.head(5)

,Id,Title,ReleaseDate,Team,Rating,TimesListed,NumberofReviews,Genres,Plays,Playing,Backlogs,Wishlist
1252,1252,Elden Ring: Shadow of the Erdtree,releases on TBD,"FromSoftware, Bandai Namco Entertainment",4.8,18,18,"Adventure, RPG",1,0,39,146
1090,1090,The Great Ace Attorney 2: Resolve,"Aug 03, 2017",Capcom,4.6,386,386,"Adventure, Point-and-Click, Puzzle, Visual Novel",1100,75,771,468
1153,1153,Dwarf Fortress,"Dec 06, 2022","Bay 12 Games, Kitfox Games",4.6,48,48,"Indie, RPG, Simulator, Strategy",225,80,181,195
1104,1104,Sekiro: Shadows Die Twice - GOTY Edition,"Oct 28, 2020","Activision, FromSoftware",4.6,173,173,"Adventure, Brawler, RPG",1400,153,461,373
43,43,Outer Wilds,"May 28, 2019","Mobius Digital, Annapurna Interactive",4.6,1800,1800,"Adventure, Indie, Puzzle, Simulator",7700,661,4800,3100

In [15]:
%store df

Stored 'df' (DataFrame)